name: martes_emp_qr
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  audioplayers: ^4.1.0
  auto_size_text: ^3.0.0
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_generator: ^2.0.0
  http: ^0.13.5
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^2.1.0
  mobile_scanner: ^2.1.0
  pie_chart: ^5.3.2
  provider: ^6.0.4
  slide_to_act: ^2.0.1
  sqflite: ^2.2.8+4
  string_validator: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
